# Generated by Django 3.2.12 on 2022-03-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220313_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='game_score',
            field=models.IntegerField(default=0),
        ),
    ]
