# Generated by Django 3.2.12 on 2022-03-08 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('incorrectAnswer1', models.CharField(blank=True, max_length=255)),
                ('incorrectAnswer2', models.CharField(blank=True, max_length=255)),
                ('incorrectAnswer3', models.CharField(blank=True, max_length=255)),
                ('correctAnswer', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
