# Generated by Django 3.2.12 on 2022-03-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0006_leaderboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='game_mode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
