# Generated by Django 3.2.12 on 2022-03-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0007_leaderboard_game_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderBoard',
        ),
    ]
