# Generated by Django 3.2.12 on 2022-03-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0014_score_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_hard',
            field=models.IntegerField(default=0),
        ),
    ]
