# Generated by Django 3.2.12 on 2022-03-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0015_score_score_hard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score_hard',
        ),
    ]
