# Generated by Django 3.2.12 on 2022-03-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0017_score_score_hard'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
