# Generated by Django 3.2.12 on 2022-03-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0018_score_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
