# Generated by Django 3.2.12 on 2022-03-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0019_question_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='date',
        ),
    ]
