# Generated by Django 3.2.12 on 2022-03-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0023_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
