# Generated by Django 3.2.12 on 2022-03-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0027_delete_score_hard'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_hard',
            field=models.IntegerField(default=0),
        ),
    ]
