# Generated by Django 3.2.12 on 2022-03-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0030_score_hard'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='hard_mode',
            field=models.BooleanField(default=False),
        ),
    ]
